### ISSUE TITLE
Plugin Exec: Name lookup can't handle nil

### ISSUE THREAD

**Issue by TheFynx** [ImperialLabs/slapi#26]
The command and argument lookup in the plugin exec function cannot handle nil responses. 

```
channel=C27MR7Y03, team=T27E7QD5Z, text=bot hello_world, ts=1476483860.000197, type=message, user=U27QQKRDX
E, [2016-10-14T17:24:20.476488 #15546] ERROR -- : undefined method `pre_match' for nil:NilClass (NoMethodError)
/Users/levi/git/github/imperiallabs/slapi/lib/core/plugins.rb:47:in `exec'
/Users/levi/git/github/imperiallabs/slapi/lib/core/realtime.rb:51:in `block in run_bot'
```

**Comment by TheFynx** [comment]
Fixed with #31 PR
